#!/usr/bin/env node
// Regenerate the derived JavaScript modules from lexer.wasm and upstream/Lexer.h:
//
//   lexer-wasm-base64.js - the WASM binary embedded as base64, so the package works
//                          in every environment without bundler configuration
//   tokens.js            - the TokenType numbering, parsed from the APPLY_FOR_TOKENS
//                          macro in Lexer.h
//
// The token table MUST be generated from the same source revision the WASM is built
// from: token types are plain enum values, and inserting a token in the middle of the
// enum renumbers everything after it (this has happened, e.g. when PipeOperator was
// added after PipeMark).

import {readFileSync, writeFileSync} from "node:fs"
import {dirname, join} from "node:path"
import {fileURLToPath} from "node:url"

const root = join(dirname(fileURLToPath(import.meta.url)), "..")

const commit = readFileSync(join(root, "upstream/COMMIT"), "utf8").trim()
const header = `// GENERATED by scripts/generate.js - do not edit.\n` +
    `// Source: ClickHouse/ClickHouse@${commit}, src/Parsers.\n`

// ---- lexer-wasm-base64.js --------------------------------------------------------

const wasm = readFileSync(join(root, "lexer.wasm"))
writeFileSync(join(root, "lexer-wasm-base64.js"),
    `${header}// To regenerate: bash scripts/build.sh && node scripts/generate.js\n` +
    `export default\n  "${wasm.toString("base64")}"\n`)

// ---- tokens.js -------------------------------------------------------------------

// Extract the M(Name) entries, in order, from the APPLY_FOR_TOKENS macro definition
// (every line of the macro ends with a backslash continuation).
const lexerH = readFileSync(join(root, "upstream/Lexer.h"), "utf8")
const lines = lexerH.split("\n")
const start = lines.findIndex(l => l.includes("#define APPLY_FOR_TOKENS"))
if (start < 0) throw new Error("APPLY_FOR_TOKENS not found in upstream/Lexer.h")

const names = []
for (let i = start; i < lines.length; i++) {
    for (const m of lines[i].matchAll(/\bM\(([A-Za-z0-9_]+)\)/g)) names.push(m[1])
    if (!lines[i].trimEnd().endsWith("\\")) break
}
if (names.length < 30 || !names.includes("EndOfStream"))
    throw new Error(`Parsed a suspicious token list (${names.length} entries) from Lexer.h`)

writeFileSync(join(root, "tokens.js"),
    header +
    `\n/// Numeric values of the TokenType enum in src/Parsers/Lexer.h. The values are\n` +
    `/// positional: they are only valid together with the lexer.wasm built from the\n` +
    `/// same ClickHouse revision, which is what this package guarantees.\n` +
    `export const TokenType = Object.freeze({\n` +
    names.map((n, i) => `  ${n}: ${i},`).join("\n") +
    `\n})\n\n` +
    `/// Token type names by numeric value.\n` +
    `export const TOKEN_NAMES = Object.freeze(${JSON.stringify(names)})\n`)

console.log(`Generated lexer-wasm-base64.js (${wasm.length} bytes of WASM) and tokens.js (${names.length} token types) from ${commit}`)
